openapi: 3.0.3
info:
  title: VouckBack
  description: |-
    Microserviço para geração de voucher como descontos em valor ou percentual paras clientes em seu ponto de venda.

    _Se você que saber mais sobre a REMATEC, então  click [aqui](http://rematecvarejo.com.br). Aproveite e nos façam uma visita!_

  contact:
    email: mario7lagoas@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11

servers:
  - url: http://localhost:8080/voucher-back/v1


tags:
  - name: Perfil
    description: Operações sobre Perfil de Usuario
paths:
  /perfil:
    get:
      tags:
        - Perfil
      summary: Buscando Lista de Perfil
      description: Buscando Lista de Perfil na Plataforma
      operationId: buscandoListaPerfil
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PerfilApiResponse'
    post:
      tags:
        - Perfil
      summary: Criando Um Perfil
      description: Criando Um Perfil na Plataforma
      operationId: criandoPerfil
      requestBody:
        description: Criando novo Perfil
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerfilApiRequest'
        required: true
      responses:
        '201':
          description: Created successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerfilApiResponse'
        '422':
          description: unprocessable operation
  /perfil/resumido:
    get:
      tags:
        - Perfil
      summary: Buscando Lista de Perfil Resumido
      description: Buscando Lista de Perfil Resumido na Plataforma
      operationId: buscandoListaResumidoPerfil
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PerfilResumidoApiResponse'
  /perfil/{guid}:
    get:
      tags:
        - Perfil
      summary: Buscando Perfil Pelo Perfil GUID
      description: Buscando Perfil Pelo Perfil GUID na Plataforma
      operationId: buscandoPerfilPeloGUID
      parameters:
        - name: guid
          in: path
          description: Informe o GUID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerfilApiResponse'
        '404':
          description: not found operation
  /perfil/{nome}/nome:
    get:
      tags:
        - Perfil
      summary: Buscando Perfil Pelo Perfil Nome
      description: Buscando Perfil Pelo Perfil Nome na Plataforma
      operationId: buscandoPerfilPeloNome
      parameters:
        - name: nome
          in: path
          description: Nome do Perfil
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerfilApiResponse'
        '404':
          description: not found operation
components:
  schemas:
    PerfilApiRequest:
      required:
        - nome
        - roles
      type: object
      properties:
        nome:
          type: string
          description: Nome do Perfil
          example: Moderator
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleApiResponse'
    PerfilResumidoApiResponse:
      type: object
      properties:
        guid:
          type: string
          example: aaaa-bbbb-cccc-dddd-eeeee
        nome:
          type: string
          example: Moderator

    PerfilApiResponse:
      properties:
        guid:
          type: string
          example: aaaa-bbbb-cccc-dddd-eeeee
        nome:
          type: string
          example: Moderator
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleApiResponse'
    RoleApiResponse:
      type: object
      properties:
        nome:
          type: string
          example: MENU_LOJA