openapi: 3.0.3
info:
  title: VouckBack
  description: |-
    Microserviço para geração de voucher como descontos em valor ou percentual paras clientes em seu ponto de venda.

    _Se você que saber mais sobre a REMATEC, então  click [aqui](http://rematecvarejo.com.br). Aproveite e nos façam uma visita!_

  contact:
    email: mario7lagoas@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11

servers:
  - url: http://localhost:8080/voucher-back/v1


tags:
  - name: Loja
    description: Operações sobre Loja
  - name: Perfil
    description: Operações sobre Perfil de Usuario
paths:
  /loja:
    get:
      tags:
        - Loja
      summary: Buscando Lista de Loja
      description: Buscando Lista de Loja na Plataforma
      operationId: buscandoListaLoja
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LojaApiResponse'
  /loja/{guid}:
    get:
      tags:
        - Loja
      summary: Buscando Loja Pelo GUID
      description: Buscando Loja Pelo GUID na Plataforma
      operationId: buscandoLojaPeloGUID
      parameters:
        - name: guid
          in: path
          description: Informe o GUID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LojaApiResponse'
        '404':
          description: not found operation
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: 404 NOT_FOUND
                  erros:
                    type: array
                    items:
                      properties:
                        codigo:
                          type: string
                          example: Não encontrado.
                        mensagem:
                          type: string
                          example: "Loja não encontrada"
  /loja/paginada:
    get:
      tags:
        - Loja
      summary: Buscando Lista de Loja Pagina
      description: Buscando Lista de Loja pagina na Plataforma
      operationId: buscandoListaPaginadaLoja
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 10
        - name: cnpj
          in: query
          schema:
            type: string
            default: ""
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:

                allOf:
                  - $ref: '#/components/schemas/PaginacaoApiResponse'
                  - type: object
                    properties:
                      lojas:
                        type: array
                        items:
                          $ref: '#/components/schemas/LojaApiResponse'
  /loja/ativa:
    get:
      tags:
        - Loja
      summary: Buscando Lista de Loja Ativa
      description: Buscando Lista de Loja Ativa na Plataforma
      operationId: buscandoListaLojaAtiva
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LojaApiResponse'
  /perfil:
    get:
      tags:
        - Perfil
      summary: Buscando Lista de Perfil
      description: Buscando Lista de Perfil na Plataforma
      operationId: buscandoListaPerfil
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PerfilApiResponse'
    post:
      tags:
        - Perfil
      summary: Criando Um Perfil
      description: Criando Um Perfil na Plataforma
      operationId: criandoPerfil
      requestBody:
        description: Criando novo Perfil
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerfilApiRequest'
        required: true
      responses:
        '201':
          description: Created successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerfilApiResponse'
        '422':
          description: unprocessable operation
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: 422 UNPROCESSABLE_ENTITY
                  erros:
                    type: array
                    items:
                      properties:
                        codigo:
                          type: string
                          example: Perfil já cadastrado.
                        mensagem:
                          type: string
                          example: Já existe um Perfil com este nome.
  /perfil/resumido:
    get:
      tags:
        - Perfil
      summary: Buscando Lista de Perfil Resumido
      description: Buscando Lista de Perfil Resumido na Plataforma
      operationId: buscandoListaResumidoPerfil
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PerfilResumidoApiResponse'
  /perfil/{guid}:
    get:
      tags:
        - Perfil
      summary: Buscando Perfil Pelo Perfil GUID
      description: Buscando Perfil Pelo Perfil GUID na Plataforma
      operationId: buscandoPerfilPeloGUID
      parameters:
        - name: guid
          in: path
          description: Informe o GUID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerfilApiResponse'
        '404':
          description: not found operation
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: 404 NOT_FOUND
                  erros:
                    type: array
                    items:
                      properties:
                        codigo:
                          type: string
                          example: Não encontrado.
                        mensagem:
                          type: string
                          example: Perfil não encontrado.
    put:
      tags:
        - Perfil
      parameters:
        - name: guid
          in: path
          description: Informe o GUID
          required: true
          schema:
            type: string
      summary: Alterando um Perfil
      description: Alterando um Perfil na Plataforma
      operationId: alterandoPerfil
      requestBody:
        description: Alterando Perfil Existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerfilApiRequest'
        required: true
      responses:
        '202':
          description: Accepted successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerfilApiResponse'
        '404':
          description: not found operation
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: 404 NOT_FOUND
                  erros:
                    type: array
                    items:
                      properties:
                        codigo:
                          type: string
                          example: Não encontrado.
                        mensagem:
                          type: string
                          example: Perfil não encontrado.
    delete:
      tags:
        - Perfil
      parameters:
        - name: guid
          in: path
          description: Informe o GUID
          required: true
          schema:
            type: string
      summary: Apagando um Perfil
      description: Apagando um Perfil na Plataforma
      operationId: apagandoPerfil
      responses:
        '204':
          description: No Content successful operation
        '404':
          description: not found operation
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: 404 NOT_FOUND
                  erros:
                    type: array
                    items:
                      properties:
                        codigo:
                          type: string
                          example: Não encontrado.
                        mensagem:
                          type: string
                          example: Perfil não encontrado.
        '422':
          description: unprocessable operation
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: 422 UNPROCESSABLE_ENTITY
                  erros:
                    type: array
                    items:
                      properties:
                        codigo:
                          type: string
                          example: Não permitido Excluir.
                        mensagem:
                          type: string
                          example: Não permitido Excluir. Perfil associado a algum Usuario.
  /perfil/{nome}/nome:
    get:
      tags:
        - Perfil
      summary: Buscando Perfil Pelo Perfil Nome
      description: Buscando Perfil Pelo Perfil Nome na Plataforma
      operationId: buscandoPerfilPeloNome
      parameters:
        - name: nome
          in: path
          description: Nome do Perfil
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerfilApiResponse'
        '404':
          description: not found operation
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: 404 NOT_FOUND
                  erros:
                    type: array
                    items:
                      properties:
                        codigo:
                          type: string
                          example: Não encontrado.
                        mensagem:
                          type: string
                          example: Perfil não encontrado.
components:
  schemas:
    PaginacaoApiResponse:
      properties:
        number:
          type: integer
          example: 0
        totalPages:
          type: integer
          example: 1
        totalElements:
          type: integer
          example: 1
    LojaApiResponse:
      properties:
        guid:
          type: string
          example: aaaa-bbbb-cccc-dddd-eeeee
        nome:
          type: string
          example: "Loja 001"
        cnpj:
          type: string
          example: "11111111111111"
        identificacao:
          type: string
          example: "0001"
        status:
          type: boolean
          example: true
        dataCadastro:
          type: string
          example: "2024-05-07 11:48:11"
    PerfilApiRequest:
      required:
        - nome
        - roles
      type: object
      properties:
        nome:
          type: string
          description: Nome do Perfil
          example: Moderator
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleApiResponse'
    PerfilResumidoApiResponse:
      type: object
      properties:
        guid:
          type: string
          example: aaaa-bbbb-cccc-dddd-eeeee
        nome:
          type: string
          example: Moderator
    PerfilApiResponse:
      properties:
        guid:
          type: string
          example: aaaa-bbbb-cccc-dddd-eeeee
        nome:
          type: string
          example: Moderator
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleApiResponse'
    RoleApiResponse:
      type: object
      properties:
        nome:
          type: string
          example: MENU_LOJA